server:
  port: 80
  servlet:
    context-path: /api
spring:
  datasource:
    #url: jdbc:oracle:thin:@localhost:1521:XE
    #url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    #username: BENEZINHO
    #password: root
    #driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:mariadb://localhost:3306/PESSOAS-2SI?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    #driver-class-name: org.mariadb.jdbc.Driver
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.OracleDialect
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        ddl-auto: create
